const FETCH_DATA = "FETCH_DATA";
const LIST_FETCHED = "LIST_FETCHED";
const API_CALLED = "API_CALLED";
const FETCH_ERROR = "FETCH_ERROR";

export const Action = { FETCH_DATA, LIST_FETCHED, API_CALLED, FETCH_ERROR };